runtime: nodejs10

instance_class: F1

env_variables:
  BUCKET_NAME: 'finance-tracker-259314.appspot.com'

handlers:
  - url: /
    static_files: build/index.html
    upload: build/index.html
  - url: /
    static_dir: build
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
